//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApplyForJob
    {
        public int IDApply { get; set; }
        public string Message { get; set; }
        public Nullable<System.DateTime> ApplyDate { get; set; }
        public Nullable<int> IDJob { get; set; }
        public Nullable<int> IDUser { get; set; }
        public string CV { get; set; }
    
        public virtual Job Job { get; set; }
        public virtual User User { get; set; }
    }
}
