//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.ApplyForJob = new HashSet<ApplyForJob>();
            this.Job = new HashSet<Job>();
        }
    
        public int IDUser { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public Nullable<int> IDTypeUser { get; set; }
        public Nullable<bool> OnLine { get; set; }
        public string Gender { get; set; }
        public string MacAddress { get; set; }
        public string Phone { get; set; }
    
        public virtual ICollection<ApplyForJob> ApplyForJob { get; set; }
        public virtual UserType UserType { get; set; }
        public virtual ICollection<Job> Job { get; set; }
    }
}
